#!/usr/bin/env python
"""Normalize the site manifest and regenerate the supported-site listing.

Run with no arguments to rewrite `sherlock_project/resources/data.json` in
normalized form (sorted, two-space indent, trailing newline) and regenerate
`docs/sites.md` from it.

Run with `--check` to verify that the manifest conforms to the bundled schema,
that it is already normalized, and that the listing is current -- without
writing anything. CI uses this so that manifest changes cannot land unsorted
or with a stale listing.
"""

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "sherlock_project" / "resources" / "data.json"
SCHEMA_PATH = REPO_ROOT / "sherlock_project" / "resources" / "data.schema.json"
SITE_LIST_PATH = REPO_ROOT / "docs" / "sites.md"

DEFAULT_ENCODING = "utf-8"
GENERATED_BY = "devel/site-list.py"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding=DEFAULT_ENCODING))


def render_manifest(data: dict) -> str:
    """Render the canonical on-disk form of the manifest."""
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def render_site_list(data: dict) -> str:
    """Render the human-readable listing of supported sites."""
    # The schema keyword is manifest metadata, not a site.
    social_networks = sorted(
        (name, info) for name, info in data.items() if name != "$schema"
    )

    # The heading deliberately does not claim to list "supported sites". This
    # renders data.json, the legacy upstream manifest, which is reachable only
    # through `--json`. The bundled WhatsMyName manifest is the default and is
    # substantially larger, so labelling this as the supported set understated
    # the shipped site list by a few hundred entries. The README carries the
    # real breakdown; no count for WMN is repeated here, because a second number
    # in a second place is a second thing to go stale.
    lines = [
        "# Legacy site list",
        "",
        f"<!-- Generated by {GENERATED_BY}. Do not edit by hand. -->",
        "",
        (
            f"The **{len(social_networks)}** sites in "
            "`sherlock_project/resources/data.json`, the legacy upstream manifest."
        ),
        "",
        "> This is **not** the list a normal scan uses. The default manifest is",
        "> the bundled WhatsMyName dataset, which is larger; see the README for",
        "> its breakdown. This listing applies only when a legacy manifest is",
        "> loaded explicitly with `--json`.",
        "",
        "Sites marked **(NSFW)** are skipped unless `--nsfw` is passed.",
        "",
    ]

    for name, info in social_networks:
        is_nsfw = " **(NSFW)**" if info.get("isNSFW") else ""
        lines.append(f"1. [{name}]({info['urlMain']}){is_nsfw}")

    return "\n".join(lines) + "\n"


def validate_against_schema(data: dict) -> None:
    """Validate the manifest against the schema bundled in this repository."""
    try:
        from jsonschema import validate
    except ImportError:
        sys.exit(
            "error: --check needs jsonschema for schema validation.\n"
            "       Install it with `pip install jsonschema`, or run "
            "`poetry install --with dev`."
        )

    validate(instance=data, schema=read_json(SCHEMA_PATH))


def report_stale(path: Path, current: str, expected: str) -> bool:
    """Print a diff for a file that is not in its generated form."""
    if current == expected:
        return False

    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=f"{path.relative_to(REPO_ROOT).as_posix()} (committed)",
        tofile=f"{path.relative_to(REPO_ROOT).as_posix()} (generated)",
        lineterm="",
        n=1,
    )
    print("\n".join(list(diff)[:60]))
    return True


def check(data: dict) -> int:
    validate_against_schema(data)

    stale = False
    stale |= report_stale(
        MANIFEST_PATH,
        MANIFEST_PATH.read_text(encoding=DEFAULT_ENCODING),
        render_manifest(data),
    )
    stale |= report_stale(
        SITE_LIST_PATH,
        SITE_LIST_PATH.read_text(encoding=DEFAULT_ENCODING)
        if SITE_LIST_PATH.exists()
        else "",
        render_site_list(data),
    )

    if stale:
        print(
            f"\nerror: manifest or site listing is not in generated form.\n"
            f"       Run `python {GENERATED_BY}` and commit the result.",
            file=sys.stderr,
        )
        return 1

    print("Manifest is valid, normalized, and the site listing is current.")
    return 0


def write(data: dict) -> int:
    MANIFEST_PATH.write_text(render_manifest(data), encoding=DEFAULT_ENCODING)
    SITE_LIST_PATH.parent.mkdir(parents=True, exist_ok=True)
    SITE_LIST_PATH.write_text(render_site_list(data), encoding=DEFAULT_ENCODING)
    print("Finished updating supported site listing!")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate and report staleness without writing. Exits non-zero "
             "if the manifest or listing needs regenerating.",
    )
    args = parser.parse_args()

    data = read_json(MANIFEST_PATH)
    return check(data) if args.check else write(data)


if __name__ == "__main__":
    raise SystemExit(main())
